package contracts

var ToDoABI = `[
    {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"taskId","type":"uint256"},{"indexed":true,"internalType":"address","name":"creator","type":"address"},{"indexed":true,"internalType":"address","name":"assignedTo","type":"address"},{"indexed":false,"internalType":"uint32","name":"date","type":"uint32"},{"indexed":false,"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TaskCreated","type":"event"},
    {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"taskId","type":"uint256"},{"indexed":true,"internalType":"address","name":"deletedBy","type":"address"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TaskDeleted","type":"event"},
    {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"taskId","type":"uint256"},{"indexed":true,"internalType":"address","name":"modifiedBy","type":"address"},{"indexed":false,"internalType":"bytes32","name":"oldDescriptionHash","type":"bytes32"},{"indexed":false,"internalType":"bytes32","name":"newDescriptionHash","type":"bytes32"},{"indexed":false,"internalType":"uint32","name":"oldDate","type":"uint32"},{"indexed":false,"internalType":"uint32","name":"newDate","type":"uint32"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TaskModified","type":"event"},
    {"anonymous":false,"inputs":[{"indexed":true,"internalType":"uint256","name":"taskId","type":"uint256"},{"indexed":false,"internalType":"address","name":"updatedBy","type":"address"},{"indexed":false,"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TaskStatusUpdated","type":"event"},
    {"inputs":[{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"}],"name":"createTask","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"uint32","name":"","type":"uint32"},{"internalType":"uint256","name":"","type":"uint256"}],"name":"dateTaskIds","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"taskId","type":"uint256"}],"name":"deleteTask","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"getActiveTaskCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[],"name":"getActiveTasks","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"internalType":"struct ToDoContract.Task[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"user","type":"address"}],"name":"getAllTasksByUser","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"internalType":"struct ToDoContract.Task[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint32","name":"date","type":"uint32"}],"name":"getTasksByDate","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"internalType":"struct ToDoContract.Task[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"enum ToDoContract.TaskStatus","name":"_status","type":"uint8"}],"name":"getTasksByStatus","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"internalType":"struct ToDoContract.Task[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint32","name":"_date","type":"uint32"}],"name":"getUserTasksByDate","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"internalType":"struct ToDoContract.Task[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"taskId","type":"uint256"},{"internalType":"string","name":"newDescription","type":"string"},{"internalType":"uint32","name":"newDate","type":"uint32"}],"name":"modifyTask","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[],"name":"taskCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"tasks","outputs":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"address","name":"creator","type":"address"},{"internalType":"address","name":"assignedTo","type":"address"},{"internalType":"string","name":"description","type":"string"},{"internalType":"uint32","name":"date","type":"uint32"},{"internalType":"enum ToDoContract.TaskStatus","name":"status","type":"uint8"},{"internalType":"bool","name":"isDeleted","type":"bool"},{"internalType":"bool","name":"isModified","type":"bool"}],"stateMutability":"view","type":"function"},
    {"inputs":[{"internalType":"uint256","name":"taskId","type":"uint256"},{"internalType":"enum ToDoContract.TaskStatus","name":"newStatus","type":"uint8"}],"name":"updateTaskStatus","outputs":[],"stateMutability":"nonpayable","type":"function"},
    {"inputs":[{"internalType":"address","name":"","type":"address"},{"internalType":"uint256","name":"","type":"uint256"}],"name":"userTaskIds","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}
]`
